[2024-03-19 12:39:25,566] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag_ml_life_cycle.get_gold_data scheduled__2024-03-19T11:58:20.308325+00:00 [queued]>
[2024-03-19 12:39:25,729] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag_ml_life_cycle.get_gold_data scheduled__2024-03-19T11:58:20.308325+00:00 [queued]>
[2024-03-19 12:39:25,729] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-19 12:39:25,729] {taskinstance.py:1239} INFO - Starting attempt 2 of 4
[2024-03-19 12:39:25,729] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-19 12:39:25,755] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): get_gold_data> on 2024-03-19 11:58:20.308325+00:00
[2024-03-19 12:39:25,774] {standard_task_runner.py:52} INFO - Started process 52936 to run task
[2024-03-19 12:39:25,795] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'dag_ml_life_cycle', 'get_gold_data', 'scheduled__2024-03-19T11:58:20.308325+00:00', '--job-id', '637', '--raw', '--subdir', 'DAGS_FOLDER/lifecycle_ml_example/dags/dag_ml_life_cycle.py', '--cfg-path', '/var/folders/t4/c2kdpvnj6r793w3k056dkc640000gp/T/tmpb5locvx_', '--error-file', '/var/folders/t4/c2kdpvnj6r793w3k056dkc640000gp/T/tmp0vaf6do4']
[2024-03-19 12:39:25,803] {standard_task_runner.py:77} INFO - Job 637: Subtask get_gold_data
[2024-03-19 12:39:25,976] {logging_mixin.py:109} INFO - Running <TaskInstance: dag_ml_life_cycle.get_gold_data scheduled__2024-03-19T11:58:20.308325+00:00 [running]> on host 1.0.0.127.in-addr.arpa
[2024-03-19 12:39:26,093] {taskinstance.py:1424} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dag_ml_life_cycle
AIRFLOW_CTX_TASK_ID=get_gold_data
AIRFLOW_CTX_EXECUTION_DATE=2024-03-19T11:58:20.308325+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-03-19T11:58:20.308325+00:00
[2024-03-19 12:39:26,097] {data_preprocessing.py:34} INFO - Random error: 0.10886154873307341
[2024-03-19 12:39:26,100] {data_preprocessing.py:38} INFO - Getting gold data
[2024-03-19 12:39:26,102] {data_preprocessing.py:42} INFO - Getting raw data from ml_lifecycle_airflow/in-vehicle-coupon-recommendation.csv ...
[2024-03-19 12:39:34,077] {data_preprocessing.py:89} INFO - Starting data preprocessing ...
[2024-03-19 12:39:34,740] {data_preprocessing.py:150} INFO - Data preprocessing complete

[2024-03-19 12:39:34,898] {data_preprocessing.py:168} INFO - Encoding features using hashing encoder ...
[2024-03-19 12:42:21,804] {data_preprocessing.py:168} INFO - Encoding features using hashing encoder ...
[2024-03-19 12:59:59,871] {local_task_job.py:191} WARNING - The recorded hostname 1.0.0.127.in-addr.arpa does not match this instance's hostname MacBook-Pro-2.local
[2024-03-19 12:59:59,888] {process_utils.py:120} INFO - Sending Signals.SIGTERM to group 52936. PIDs of all processes in the group: [53171, 56636, 56731, 56826, 56913, 52936]
[2024-03-19 12:59:59,888] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 52936
[2024-03-19 12:59:59,889] {taskinstance.py:1408} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-03-19 12:59:59,905] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/src/features/data_preprocessing.py", line 60, in get_gold_data
    x_test_hashing = encode_features(x_test)
  File "/Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/src/features/data_preprocessing.py", line 173, in encode_features
    hashing_ros_enc = hashing_ros_enc_instance.fit(X=x)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/category_encoders/utils.py", line 315, in fit
    X_transformed = self.transform(X, override_return_df=True)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/sklearn/utils/_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/category_encoders/utils.py", line 488, in transform
    X = self._transform(X)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/category_encoders/hashing.py", line 177, in _transform
    hashing_parts = multiprocessing.Manager().Queue()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/managers.py", line 558, in start
    self._address = reader.recv()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1410, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-03-19 12:59:59,913] {taskinstance.py:1267} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_ml_life_cycle, task_id=get_gold_data, execution_date=20240319T115820, start_date=20240319T173925, end_date=20240319T175959
[2024-03-19 12:59:59,923] {standard_task_runner.py:89} ERROR - Failed to execute job 637 for task get_gold_data
Traceback (most recent call last):
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/src/features/data_preprocessing.py", line 60, in get_gold_data
    x_test_hashing = encode_features(x_test)
  File "/Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/src/features/data_preprocessing.py", line 173, in encode_features
    hashing_ros_enc = hashing_ros_enc_instance.fit(X=x)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/category_encoders/utils.py", line 315, in fit
    X_transformed = self.transform(X, override_return_df=True)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/sklearn/utils/_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/category_encoders/utils.py", line 488, in transform
    X = self._transform(X)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/category_encoders/hashing.py", line 177, in _transform
    hashing_parts = multiprocessing.Manager().Queue()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/managers.py", line 558, in start
    self._address = reader.recv()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1410, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-03-19 12:59:59,948] {process_utils.py:70} INFO - Process psutil.Process(pid=52936, status='terminated', exitcode=1, started='12:39:25') (52936) terminated with exit code 1
[2024-03-19 12:59:59,948] {process_utils.py:70} INFO - Process psutil.Process(pid=56913, status='terminated', started='12:42:34') (56913) terminated with exit code None
[2024-03-19 12:59:59,949] {process_utils.py:70} INFO - Process psutil.Process(pid=56826, status='terminated', started='12:42:30') (56826) terminated with exit code None
[2024-03-19 12:59:59,949] {process_utils.py:70} INFO - Process psutil.Process(pid=56731, status='terminated', started='12:42:26') (56731) terminated with exit code None
[2024-03-19 12:59:59,949] {process_utils.py:70} INFO - Process psutil.Process(pid=53171, status='terminated', started='12:39:34') (53171) terminated with exit code None
[2024-03-19 12:59:59,949] {process_utils.py:70} INFO - Process psutil.Process(pid=56636, status='terminated', started='12:42:21') (56636) terminated with exit code None
