[2024-03-18 18:00:59,446] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag_ml_life_cycle.get_gold_data scheduled__2024-03-18T17:30:47.382372+00:00 [queued]>
[2024-03-18 18:00:59,640] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag_ml_life_cycle.get_gold_data scheduled__2024-03-18T17:30:47.382372+00:00 [queued]>
[2024-03-18 18:00:59,641] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-18 18:00:59,641] {taskinstance.py:1239} INFO - Starting attempt 2 of 4
[2024-03-18 18:00:59,641] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-18 18:00:59,666] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): get_gold_data> on 2024-03-18 17:30:47.382372+00:00
[2024-03-18 18:00:59,690] {standard_task_runner.py:52} INFO - Started process 44072 to run task
[2024-03-18 18:00:59,713] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'dag_ml_life_cycle', 'get_gold_data', 'scheduled__2024-03-18T17:30:47.382372+00:00', '--job-id', '163', '--raw', '--subdir', 'DAGS_FOLDER/lifecycle_ml_example/dags/dag_ml_life_cycle.py', '--cfg-path', '/var/folders/t4/c2kdpvnj6r793w3k056dkc640000gp/T/tmppn7vxql_', '--error-file', '/var/folders/t4/c2kdpvnj6r793w3k056dkc640000gp/T/tmpmfjdxn5o']
[2024-03-18 18:00:59,722] {standard_task_runner.py:77} INFO - Job 163: Subtask get_gold_data
[2024-03-18 18:00:59,915] {logging_mixin.py:109} INFO - Running <TaskInstance: dag_ml_life_cycle.get_gold_data scheduled__2024-03-18T17:30:47.382372+00:00 [running]> on host 1.0.0.127.in-addr.arpa
[2024-03-18 18:01:00,047] {taskinstance.py:1424} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dag_ml_life_cycle
AIRFLOW_CTX_TASK_ID=get_gold_data
AIRFLOW_CTX_EXECUTION_DATE=2024-03-18T17:30:47.382372+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-03-18T17:30:47.382372+00:00
[2024-03-18 18:01:00,067] {data_preprocessing.py:34} INFO - Random error: 0.004988781822471311
[2024-03-18 18:01:00,070] {data_preprocessing.py:38} INFO - Getting gold data
[2024-03-18 18:01:00,072] {data_preprocessing.py:42} INFO - Getting raw data from ml_lifecycle_airflow/in-vehicle-coupon-recommendation.csv ...
[2024-03-18 18:01:16,045] {data_preprocessing.py:89} INFO - Starting data preprocessing ...
[2024-03-18 18:01:16,739] {data_preprocessing.py:150} INFO - Data preprocessing complete

[2024-03-18 18:01:16,921] {data_preprocessing.py:168} INFO - Encoding features using hashing encoder ...
[2024-03-18 18:08:14,803] {local_task_job.py:191} WARNING - The recorded hostname 1.0.0.127.in-addr.arpa does not match this instance's hostname MacBook-Pro-2.local
[2024-03-18 18:08:14,833] {process_utils.py:120} INFO - Sending Signals.SIGTERM to group 44072. PIDs of all processes in the group: [44298, 44299, 44345, 44389, 44438, 44072]
[2024-03-18 18:08:14,834] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 44072
[2024-03-18 18:08:14,835] {taskinstance.py:1408} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-03-18 18:08:14,867] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/src/features/data_preprocessing.py", line 59, in get_gold_data
    x_train_hashing = encode_features(x_train)
  File "/Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/src/features/data_preprocessing.py", line 173, in encode_features
    hashing_ros_enc = hashing_ros_enc_instance.fit(X=x)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/category_encoders/utils.py", line 315, in fit
    X_transformed = self.transform(X, override_return_df=True)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/sklearn/utils/_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/category_encoders/utils.py", line 488, in transform
    X = self._transform(X)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/category_encoders/hashing.py", line 177, in _transform
    hashing_parts = multiprocessing.Manager().Queue()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/managers.py", line 558, in start
    self._address = reader.recv()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1410, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-03-18 18:08:14,887] {taskinstance.py:1267} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_ml_life_cycle, task_id=get_gold_data, execution_date=20240318T173047, start_date=20240318T230059, end_date=20240318T230814
[2024-03-18 18:08:14,903] {standard_task_runner.py:89} ERROR - Failed to execute job 163 for task get_gold_data
Traceback (most recent call last):
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/src/features/data_preprocessing.py", line 59, in get_gold_data
    x_train_hashing = encode_features(x_train)
  File "/Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/src/features/data_preprocessing.py", line 173, in encode_features
    hashing_ros_enc = hashing_ros_enc_instance.fit(X=x)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/category_encoders/utils.py", line 315, in fit
    X_transformed = self.transform(X, override_return_df=True)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/sklearn/utils/_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/category_encoders/utils.py", line 488, in transform
    X = self._transform(X)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/category_encoders/hashing.py", line 177, in _transform
    hashing_parts = multiprocessing.Manager().Queue()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/managers.py", line 558, in start
    self._address = reader.recv()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1410, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-03-18 18:08:14,944] {process_utils.py:70} INFO - Process psutil.Process(pid=44389, status='terminated', started='18:01:25') (44389) terminated with exit code None
[2024-03-18 18:08:14,945] {process_utils.py:70} INFO - Process psutil.Process(pid=44072, status='terminated', exitcode=1, started='18:00:59') (44072) terminated with exit code 1
[2024-03-18 18:08:14,945] {process_utils.py:70} INFO - Process psutil.Process(pid=44438, status='terminated', started='18:01:30') (44438) terminated with exit code None
[2024-03-18 18:08:14,946] {process_utils.py:70} INFO - Process psutil.Process(pid=44298, status='terminated', started='18:01:16') (44298) terminated with exit code None
[2024-03-18 18:08:14,946] {process_utils.py:70} INFO - Process psutil.Process(pid=44299, status='terminated', started='18:01:16') (44299) terminated with exit code None
[2024-03-18 18:08:14,946] {process_utils.py:70} INFO - Process psutil.Process(pid=44345, status='terminated', started='18:01:21') (44345) terminated with exit code None
