[2024-03-19 04:05:34,367] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag_ml_life_cycle.evaluate_model scheduled__2024-03-18T23:43:39.086022+00:00 [queued]>
[2024-03-19 04:05:34,539] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag_ml_life_cycle.evaluate_model scheduled__2024-03-18T23:43:39.086022+00:00 [queued]>
[2024-03-19 04:05:34,539] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-19 04:05:34,540] {taskinstance.py:1239} INFO - Starting attempt 1 of 4
[2024-03-19 04:05:34,540] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-19 04:05:34,564] {taskinstance.py:1259} INFO - Executing <Task(_PythonDecoratedOperator): evaluate_model> on 2024-03-18 23:43:39.086022+00:00
[2024-03-19 04:05:34,582] {standard_task_runner.py:52} INFO - Started process 85450 to run task
[2024-03-19 04:05:34,604] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'dag_ml_life_cycle', 'evaluate_model', 'scheduled__2024-03-18T23:43:39.086022+00:00', '--job-id', '351', '--raw', '--subdir', 'DAGS_FOLDER/lifecycle_ml_example/dags/dag_ml_life_cycle.py', '--cfg-path', '/var/folders/t4/c2kdpvnj6r793w3k056dkc640000gp/T/tmp75wbqlck', '--error-file', '/var/folders/t4/c2kdpvnj6r793w3k056dkc640000gp/T/tmp8gcpdqrf']
[2024-03-19 04:05:34,612] {standard_task_runner.py:77} INFO - Job 351: Subtask evaluate_model
[2024-03-19 04:05:34,768] {logging_mixin.py:109} INFO - Running <TaskInstance: dag_ml_life_cycle.evaluate_model scheduled__2024-03-18T23:43:39.086022+00:00 [running]> on host 1.0.0.127.in-addr.arpa
[2024-03-19 04:05:34,890] {taskinstance.py:1424} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dag_ml_life_cycle
AIRFLOW_CTX_TASK_ID=evaluate_model
AIRFLOW_CTX_EXECUTION_DATE=2024-03-18T23:43:39.086022+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-03-18T23:43:39.086022+00:00
[2024-03-19 04:05:34,893] {dag_ml_life_cycle.py:93} INFO - Getting gold data from ml_lifecycle_airflow/in-vehicle-coupon-recommendation_gold.csv ...
[2024-03-19 04:11:32,769] {local_task_job.py:191} WARNING - The recorded hostname 1.0.0.127.in-addr.arpa does not match this instance's hostname MacBook-Pro-2.local
[2024-03-19 04:11:32,782] {process_utils.py:120} INFO - Sending Signals.SIGTERM to group 85450. PIDs of all processes in the group: [85562, 85450]
[2024-03-19 04:11:32,782] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 85450
[2024-03-19 04:11:32,783] {taskinstance.py:1408} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-03-19 04:11:32,793] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/dags/dag_ml_life_cycle.py", line 97, in evaluate_model_task
    y_train = get_blob_as_dataframe(
  File "/Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/src/utils/f_gcs_storage.py", line 121, in get_blob_as_dataframe
    storage_client = storage.Client()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/cloud/storage/client.py", line 226, in __init__
    super(Client, self).__init__(
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/cloud/client/__init__.py", line 320, in __init__
    _ClientProjectMixin.__init__(self, project=project, credentials=credentials)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/cloud/client/__init__.py", line 268, in __init__
    project = self._determine_default(project)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/cloud/client/__init__.py", line 287, in _determine_default
    return _determine_default_project(project)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/cloud/_helpers/__init__.py", line 152, in _determine_default_project
    _, project = google.auth.default()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/auth/_default.py", line 657, in default
    credentials, project_id = checker()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/auth/_default.py", line 651, in <lambda>
    lambda: _get_gcloud_sdk_credentials(quota_project_id=quota_project_id),
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/auth/_default.py", line 242, in _get_gcloud_sdk_credentials
    project_id = _cloud_sdk.get_project_id()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/auth/_cloud_sdk.py", line 106, in get_project_id
    project = _run_subprocess_ignore_stderr(
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/auth/_cloud_sdk.py", line 88, in _run_subprocess_ignore_stderr
    output = subprocess.check_output(command, stderr=devnull)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/subprocess.py", line 507, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/subprocess.py", line 1121, in communicate
    stdout = self.stdout.read()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1410, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-03-19 04:11:32,799] {taskinstance.py:1267} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_ml_life_cycle, task_id=evaluate_model, execution_date=20240318T234339, start_date=20240319T090534, end_date=20240319T091132
[2024-03-19 04:11:32,806] {standard_task_runner.py:89} ERROR - Failed to execute job 351 for task evaluate_model
Traceback (most recent call last):
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/dags/dag_ml_life_cycle.py", line 97, in evaluate_model_task
    y_train = get_blob_as_dataframe(
  File "/Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/src/utils/f_gcs_storage.py", line 121, in get_blob_as_dataframe
    storage_client = storage.Client()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/cloud/storage/client.py", line 226, in __init__
    super(Client, self).__init__(
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/cloud/client/__init__.py", line 320, in __init__
    _ClientProjectMixin.__init__(self, project=project, credentials=credentials)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/cloud/client/__init__.py", line 268, in __init__
    project = self._determine_default(project)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/cloud/client/__init__.py", line 287, in _determine_default
    return _determine_default_project(project)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/cloud/_helpers/__init__.py", line 152, in _determine_default_project
    _, project = google.auth.default()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/auth/_default.py", line 657, in default
    credentials, project_id = checker()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/auth/_default.py", line 651, in <lambda>
    lambda: _get_gcloud_sdk_credentials(quota_project_id=quota_project_id),
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/auth/_default.py", line 242, in _get_gcloud_sdk_credentials
    project_id = _cloud_sdk.get_project_id()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/auth/_cloud_sdk.py", line 106, in get_project_id
    project = _run_subprocess_ignore_stderr(
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/auth/_cloud_sdk.py", line 88, in _run_subprocess_ignore_stderr
    output = subprocess.check_output(command, stderr=devnull)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/subprocess.py", line 507, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/subprocess.py", line 1121, in communicate
    stdout = self.stdout.read()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1410, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-03-19 04:11:32,840] {process_utils.py:70} INFO - Process psutil.Process(pid=85450, status='terminated', exitcode=1, started='04:05:34') (85450) terminated with exit code 1
[2024-03-19 04:11:32,841] {process_utils.py:70} INFO - Process psutil.Process(pid=85562, status='terminated', started='04:05:41') (85562) terminated with exit code None
