[2024-03-19 09:36:17,742] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag_ml_life_cycle.get_gold_data scheduled__2024-03-19T09:10:57.901829+00:00 [queued]>
[2024-03-19 09:36:17,801] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag_ml_life_cycle.get_gold_data scheduled__2024-03-19T09:10:57.901829+00:00 [queued]>
[2024-03-19 09:36:17,802] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-19 09:36:17,802] {taskinstance.py:1239} INFO - Starting attempt 1 of 4
[2024-03-19 09:36:17,802] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-19 09:36:17,810] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): get_gold_data> on 2024-03-19 09:10:57.901829+00:00
[2024-03-19 09:36:17,816] {standard_task_runner.py:52} INFO - Started process 91739 to run task
[2024-03-19 09:36:17,822] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'dag_ml_life_cycle', 'get_gold_data', 'scheduled__2024-03-19T09:10:57.901829+00:00', '--job-id', '493', '--raw', '--subdir', 'DAGS_FOLDER/lifecycle_ml_example/dags/dag_ml_life_cycle.py', '--cfg-path', '/var/folders/t4/c2kdpvnj6r793w3k056dkc640000gp/T/tmpl33t_n11', '--error-file', '/var/folders/t4/c2kdpvnj6r793w3k056dkc640000gp/T/tmp8q9v1t9h']
[2024-03-19 09:36:17,825] {standard_task_runner.py:77} INFO - Job 493: Subtask get_gold_data
[2024-03-19 09:36:17,864] {logging_mixin.py:109} INFO - Running <TaskInstance: dag_ml_life_cycle.get_gold_data scheduled__2024-03-19T09:10:57.901829+00:00 [running]> on host 1.0.0.127.in-addr.arpa
[2024-03-19 09:36:17,891] {taskinstance.py:1424} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dag_ml_life_cycle
AIRFLOW_CTX_TASK_ID=get_gold_data
AIRFLOW_CTX_EXECUTION_DATE=2024-03-19T09:10:57.901829+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-03-19T09:10:57.901829+00:00
[2024-03-19 09:36:17,892] {data_preprocessing.py:34} INFO - Random error: 0.14816574750076195
[2024-03-19 09:36:17,893] {data_preprocessing.py:38} INFO - Getting gold data
[2024-03-19 09:36:17,893] {data_preprocessing.py:42} INFO - Getting raw data from ml_lifecycle_airflow/in-vehicle-coupon-recommendation.csv ...
[2024-03-19 09:36:20,225] {data_preprocessing.py:89} INFO - Starting data preprocessing ...
[2024-03-19 09:36:20,351] {data_preprocessing.py:150} INFO - Data preprocessing complete

[2024-03-19 09:36:20,378] {data_preprocessing.py:168} INFO - Encoding features using hashing encoder ...
[2024-03-19 09:37:19,153] {local_task_job.py:191} WARNING - The recorded hostname 1.0.0.127.in-addr.arpa does not match this instance's hostname 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2024-03-19 09:37:19,164] {process_utils.py:120} INFO - Sending Signals.SIGTERM to group 91739. PIDs of all processes in the group: [91804, 91805, 91829, 91830, 91857, 92180, 92265, 91739]
[2024-03-19 09:37:19,164] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 91739
[2024-03-19 09:37:19,165] {taskinstance.py:1408} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-03-19 09:37:19,177] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/src/features/data_preprocessing.py", line 59, in get_gold_data
    x_train_hashing = encode_features(x_train)
  File "/Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/src/features/data_preprocessing.py", line 173, in encode_features
    hashing_ros_enc = hashing_ros_enc_instance.fit(X=x)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/category_encoders/utils.py", line 315, in fit
    X_transformed = self.transform(X, override_return_df=True)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/sklearn/utils/_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/category_encoders/utils.py", line 488, in transform
    X = self._transform(X)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/category_encoders/hashing.py", line 194, in _transform
    process.start()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 62, in _launch
    f.write(fp.getbuffer())
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1410, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-03-19 09:37:19,182] {taskinstance.py:1267} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_ml_life_cycle, task_id=get_gold_data, execution_date=20240319T091057, start_date=20240319T143617, end_date=20240319T143719
[2024-03-19 09:37:19,189] {standard_task_runner.py:89} ERROR - Failed to execute job 493 for task get_gold_data
Traceback (most recent call last):
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/src/features/data_preprocessing.py", line 59, in get_gold_data
    x_train_hashing = encode_features(x_train)
  File "/Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/src/features/data_preprocessing.py", line 173, in encode_features
    hashing_ros_enc = hashing_ros_enc_instance.fit(X=x)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/category_encoders/utils.py", line 315, in fit
    X_transformed = self.transform(X, override_return_df=True)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/sklearn/utils/_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/category_encoders/utils.py", line 488, in transform
    X = self._transform(X)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/category_encoders/hashing.py", line 194, in _transform
    process.start()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 62, in _launch
    f.write(fp.getbuffer())
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1410, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-03-19 09:37:19,228] {process_utils.py:70} INFO - Process psutil.Process(pid=91830, status='terminated', started='09:36:21') (91830) terminated with exit code None
[2024-03-19 09:37:19,229] {process_utils.py:70} INFO - Process psutil.Process(pid=92180, status='terminated', started='09:36:53') (92180) terminated with exit code None
[2024-03-19 09:37:19,230] {process_utils.py:70} INFO - Process psutil.Process(pid=92265, status='terminated', started='09:37:01') (92265) terminated with exit code None
[2024-03-19 09:37:19,230] {process_utils.py:70} INFO - Process psutil.Process(pid=91829, status='terminated', started='09:36:21') (91829) terminated with exit code None
[2024-03-19 09:37:19,230] {process_utils.py:70} INFO - Process psutil.Process(pid=91739, status='terminated', exitcode=1, started='09:36:17') (91739) terminated with exit code 1
[2024-03-19 09:37:19,231] {process_utils.py:70} INFO - Process psutil.Process(pid=91804, status='terminated', started='09:36:20') (91804) terminated with exit code None
[2024-03-19 09:37:19,231] {process_utils.py:70} INFO - Process psutil.Process(pid=91857, status='terminated', started='09:36:24') (91857) terminated with exit code None
[2024-03-19 09:37:19,231] {process_utils.py:70} INFO - Process psutil.Process(pid=91805, status='terminated', started='09:36:20') (91805) terminated with exit code None
