[2024-03-18 08:58:05,998] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag_ml_life_cycle.make_training scheduled__2024-03-18T08:51:23.641670+00:00 [queued]>
[2024-03-18 08:58:06,058] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag_ml_life_cycle.make_training scheduled__2024-03-18T08:51:23.641670+00:00 [queued]>
[2024-03-18 08:58:06,058] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-18 08:58:06,058] {taskinstance.py:1239} INFO - Starting attempt 1 of 4
[2024-03-18 08:58:06,058] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-18 08:58:06,065] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): make_training> on 2024-03-18 08:51:23.641670+00:00
[2024-03-18 08:58:06,070] {standard_task_runner.py:52} INFO - Started process 27701 to run task
[2024-03-18 08:58:06,076] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'dag_ml_life_cycle', 'make_training', 'scheduled__2024-03-18T08:51:23.641670+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/lifecycle_ml_example/dags/dag_ml_life_cycle.py', '--cfg-path', '/var/folders/t4/c2kdpvnj6r793w3k056dkc640000gp/T/tmpp3232akk', '--error-file', '/var/folders/t4/c2kdpvnj6r793w3k056dkc640000gp/T/tmpoykzoiqc']
[2024-03-18 08:58:06,078] {standard_task_runner.py:77} INFO - Job 12: Subtask make_training
[2024-03-18 08:58:06,116] {logging_mixin.py:109} INFO - Running <TaskInstance: dag_ml_life_cycle.make_training scheduled__2024-03-18T08:51:23.641670+00:00 [running]> on host 1.0.0.127.in-addr.arpa
[2024-03-18 08:58:06,145] {taskinstance.py:1424} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dag_ml_life_cycle
AIRFLOW_CTX_TASK_ID=make_training
AIRFLOW_CTX_EXECUTION_DATE=2024-03-18T08:51:23.641670+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-03-18T08:51:23.641670+00:00
[2024-03-18 08:58:06,146] {logging_mixin.py:109} WARNING - --- Logging error ---
[2024-03-18 08:58:06,148] {logging_mixin.py:109} WARNING - Traceback (most recent call last):
[2024-03-18 08:58:06,148] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/logging/__init__.py", line 1087, in emit
    self.flush()
[2024-03-18 08:58:06,149] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/logging/__init__.py", line 1067, in flush
    self.stream.flush()
[2024-03-18 08:58:06,149] {logging_mixin.py:109} WARNING - BrokenPipeError: [Errno 32] Broken pipe
[2024-03-18 08:58:06,149] {logging_mixin.py:109} WARNING - Call stack:
[2024-03-18 08:58:06,153] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/bin/airflow", line 8, in <module>
    sys.exit(main())
[2024-03-18 08:58:06,153] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/__main__.py", line 48, in main
    args.func(args)
[2024-03-18 08:58:06,153] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
[2024-03-18 08:58:06,153] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
[2024-03-18 08:58:06,154] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
[2024-03-18 08:58:06,154] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 105, in _run_task_by_selected_method
    _run_task_by_local_task_job(args, ti)
[2024-03-18 08:58:06,154] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 163, in _run_task_by_local_task_job
    run_job.run()
[2024-03-18 08:58:06,154] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/jobs/base_job.py", line 245, in run
    self._execute()
[2024-03-18 08:58:06,154] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/jobs/local_task_job.py", line 103, in _execute
    self.task_runner.start()
[2024-03-18 08:58:06,155] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 41, in start
    self.process = self._start_by_fork()
[2024-03-18 08:58:06,155] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
[2024-03-18 08:58:06,155] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
[2024-03-18 08:58:06,155] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
[2024-03-18 08:58:06,156] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
[2024-03-18 08:58:06,156] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
[2024-03-18 08:58:06,156] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
[2024-03-18 08:58:06,156] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
[2024-03-18 08:58:06,157] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
[2024-03-18 08:58:06,157] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
[2024-03-18 08:58:06,157] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
[2024-03-18 08:58:06,157] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
[2024-03-18 08:58:06,157] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2024-03-18 08:58:06,158] {logging_mixin.py:109} WARNING -   File "/Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/src/models/training.py", line 31, in make_training
    logger.info(f"Get training data for {model_name} model ...")
[2024-03-18 08:58:06,158] {logging_mixin.py:109} WARNING - Message: 'Get training data for xgboost model ...'
Arguments: ()
[2024-03-18 08:58:06,146] {training.py:31} INFO - Get training data for xgboost model ...
[2024-03-18 08:58:10,166] {logging_mixin.py:109} WARNING - --- Logging error ---
[2024-03-18 08:58:10,166] {logging_mixin.py:109} WARNING - Traceback (most recent call last):
[2024-03-18 08:58:10,167] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/logging/__init__.py", line 1087, in emit
    self.flush()
[2024-03-18 08:58:10,167] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/logging/__init__.py", line 1067, in flush
    self.stream.flush()
[2024-03-18 08:58:10,167] {logging_mixin.py:109} WARNING - BrokenPipeError: [Errno 32] Broken pipe
[2024-03-18 08:58:10,168] {logging_mixin.py:109} WARNING - Call stack:
[2024-03-18 08:58:10,168] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/bin/airflow", line 8, in <module>
    sys.exit(main())
[2024-03-18 08:58:10,169] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/__main__.py", line 48, in main
    args.func(args)
[2024-03-18 08:58:10,169] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
[2024-03-18 08:58:10,169] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
[2024-03-18 08:58:10,169] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
[2024-03-18 08:58:10,170] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 105, in _run_task_by_selected_method
    _run_task_by_local_task_job(args, ti)
[2024-03-18 08:58:10,170] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 163, in _run_task_by_local_task_job
    run_job.run()
[2024-03-18 08:58:10,170] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/jobs/base_job.py", line 245, in run
    self._execute()
[2024-03-18 08:58:10,170] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/jobs/local_task_job.py", line 103, in _execute
    self.task_runner.start()
[2024-03-18 08:58:10,171] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 41, in start
    self.process = self._start_by_fork()
[2024-03-18 08:58:10,171] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
[2024-03-18 08:58:10,171] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
[2024-03-18 08:58:10,172] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
[2024-03-18 08:58:10,172] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
[2024-03-18 08:58:10,172] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
[2024-03-18 08:58:10,172] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
[2024-03-18 08:58:10,173] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
[2024-03-18 08:58:10,173] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
[2024-03-18 08:58:10,173] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
[2024-03-18 08:58:10,173] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
[2024-03-18 08:58:10,173] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
[2024-03-18 08:58:10,174] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2024-03-18 08:58:10,174] {logging_mixin.py:109} WARNING -   File "/Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/src/models/training.py", line 41, in make_training
    logger.info(f"Training {model_name} model.")
[2024-03-18 08:58:10,174] {logging_mixin.py:109} WARNING - Message: 'Training xgboost model.'
Arguments: ()
[2024-03-18 08:58:10,165] {training.py:41} INFO - Training xgboost model.
[2024-03-18 08:58:10,182] {logging_mixin.py:109} WARNING - /Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/xgboost/sklearn.py:1395 UserWarning: `use_label_encoder` is deprecated in 1.7.0.
[2024-03-18 08:58:10,758] {logging_mixin.py:109} WARNING - --- Logging error ---
[2024-03-18 08:58:10,758] {logging_mixin.py:109} WARNING - Traceback (most recent call last):
[2024-03-18 08:58:10,758] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/logging/__init__.py", line 1087, in emit
    self.flush()
[2024-03-18 08:58:10,759] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/logging/__init__.py", line 1067, in flush
    self.stream.flush()
[2024-03-18 08:58:10,759] {logging_mixin.py:109} WARNING - BrokenPipeError: [Errno 32] Broken pipe
[2024-03-18 08:58:10,759] {logging_mixin.py:109} WARNING - Call stack:
[2024-03-18 08:58:10,760] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/bin/airflow", line 8, in <module>
    sys.exit(main())
[2024-03-18 08:58:10,760] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/__main__.py", line 48, in main
    args.func(args)
[2024-03-18 08:58:10,761] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
[2024-03-18 08:58:10,761] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
[2024-03-18 08:58:10,761] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
[2024-03-18 08:58:10,762] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 105, in _run_task_by_selected_method
    _run_task_by_local_task_job(args, ti)
[2024-03-18 08:58:10,762] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 163, in _run_task_by_local_task_job
    run_job.run()
[2024-03-18 08:58:10,762] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/jobs/base_job.py", line 245, in run
    self._execute()
[2024-03-18 08:58:10,763] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/jobs/local_task_job.py", line 103, in _execute
    self.task_runner.start()
[2024-03-18 08:58:10,763] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 41, in start
    self.process = self._start_by_fork()
[2024-03-18 08:58:10,763] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
[2024-03-18 08:58:10,764] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
[2024-03-18 08:58:10,764] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
[2024-03-18 08:58:10,764] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
[2024-03-18 08:58:10,764] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
[2024-03-18 08:58:10,765] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
[2024-03-18 08:58:10,765] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
[2024-03-18 08:58:10,765] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
[2024-03-18 08:58:10,766] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
[2024-03-18 08:58:10,766] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
[2024-03-18 08:58:10,766] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
[2024-03-18 08:58:10,766] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2024-03-18 08:58:10,767] {logging_mixin.py:109} WARNING -   File "/Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/src/models/training.py", line 58, in make_training
    path_save_model_local = save_model(model, path_save_model)
[2024-03-18 08:58:10,767] {logging_mixin.py:109} WARNING -   File "/Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/src/models/training.py", line 89, in save_model
    logger.info(f"Model saved at {full_path_save_model}")
[2024-03-18 08:58:10,767] {logging_mixin.py:109} WARNING - Message: 'Model saved at /Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/artifacts/model.pkl'
Arguments: ()
[2024-03-18 08:58:10,757] {training.py:89} INFO - Model saved at /Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/artifacts/model.pkl
[2024-03-18 08:58:10,768] {logging_mixin.py:109} WARNING - --- Logging error ---
[2024-03-18 08:58:10,769] {logging_mixin.py:109} WARNING - Traceback (most recent call last):
[2024-03-18 08:58:10,769] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/logging/__init__.py", line 1087, in emit
    self.flush()
[2024-03-18 08:58:10,769] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/logging/__init__.py", line 1067, in flush
    self.stream.flush()
[2024-03-18 08:58:10,770] {logging_mixin.py:109} WARNING - BrokenPipeError: [Errno 32] Broken pipe
[2024-03-18 08:58:10,770] {logging_mixin.py:109} WARNING - Call stack:
[2024-03-18 08:58:10,771] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/bin/airflow", line 8, in <module>
    sys.exit(main())
[2024-03-18 08:58:10,771] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/__main__.py", line 48, in main
    args.func(args)
[2024-03-18 08:58:10,771] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
[2024-03-18 08:58:10,772] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
[2024-03-18 08:58:10,772] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
[2024-03-18 08:58:10,772] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 105, in _run_task_by_selected_method
    _run_task_by_local_task_job(args, ti)
[2024-03-18 08:58:10,773] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 163, in _run_task_by_local_task_job
    run_job.run()
[2024-03-18 08:58:10,773] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/jobs/base_job.py", line 245, in run
    self._execute()
[2024-03-18 08:58:10,773] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/jobs/local_task_job.py", line 103, in _execute
    self.task_runner.start()
[2024-03-18 08:58:10,773] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 41, in start
    self.process = self._start_by_fork()
[2024-03-18 08:58:10,774] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
[2024-03-18 08:58:10,774] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
[2024-03-18 08:58:10,774] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
[2024-03-18 08:58:10,775] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
[2024-03-18 08:58:10,775] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
[2024-03-18 08:58:10,775] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
[2024-03-18 08:58:10,776] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
[2024-03-18 08:58:10,776] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
[2024-03-18 08:58:10,776] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
[2024-03-18 08:58:10,777] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
[2024-03-18 08:58:10,777] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
[2024-03-18 08:58:10,777] {logging_mixin.py:109} WARNING -   File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2024-03-18 08:58:10,777] {logging_mixin.py:109} WARNING -   File "/Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/src/models/training.py", line 62, in make_training
    logger.info(f"Saving {model_name} model to {path_save_model} ...")
[2024-03-18 08:58:10,778] {logging_mixin.py:109} WARNING - Message: 'Saving xgboost model to artifacts/model.pkl ...'
Arguments: ()
[2024-03-18 08:58:10,768] {training.py:62} INFO - Saving xgboost model to artifacts/model.pkl ...
[2024-03-18 08:58:13,263] {logging_mixin.py:109} INFO - File: /Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/artifacts/model.pkl upload to artifacts/model.pkl.
[2024-03-18 08:58:13,264] {python.py:175} INFO - Done. Returned value was: True
[2024-03-18 08:58:13,274] {taskinstance.py:1267} INFO - Marking task as SUCCESS. dag_id=dag_ml_life_cycle, task_id=make_training, execution_date=20240318T085123, start_date=20240318T135805, end_date=20240318T135813
[2024-03-18 08:58:13,317] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-18 08:58:13,334] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
