[2024-03-12 15:05:54,328] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag_ml_life_cycle.get_gold_data manual__2024-03-12T20:05:46.726729+00:00 [queued]>
[2024-03-12 15:05:54,404] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag_ml_life_cycle.get_gold_data manual__2024-03-12T20:05:46.726729+00:00 [queued]>
[2024-03-12 15:05:54,405] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-12 15:05:54,405] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-12 15:05:54,405] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-12 15:05:54,412] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): get_gold_data> on 2024-03-12 20:05:46.726729+00:00
[2024-03-12 15:05:54,420] {standard_task_runner.py:52} INFO - Started process 84618 to run task
[2024-03-12 15:05:54,428] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'dag_ml_life_cycle', 'get_gold_data', 'manual__2024-03-12T20:05:46.726729+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/lifecycle_ml_example/dags/dag_ml_life_cycle.py', '--cfg-path', '/var/folders/t4/c2kdpvnj6r793w3k056dkc640000gp/T/tmp48uyadjk', '--error-file', '/var/folders/t4/c2kdpvnj6r793w3k056dkc640000gp/T/tmpa0n7jmis']
[2024-03-12 15:05:54,431] {standard_task_runner.py:77} INFO - Job 14: Subtask get_gold_data
[2024-03-12 15:05:54,485] {logging_mixin.py:109} INFO - Running <TaskInstance: dag_ml_life_cycle.get_gold_data manual__2024-03-12T20:05:46.726729+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2024-03-12 15:05:54,527] {taskinstance.py:1424} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dag_ml_life_cycle
AIRFLOW_CTX_TASK_ID=get_gold_data
AIRFLOW_CTX_EXECUTION_DATE=2024-03-12T20:05:46.726729+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-03-12T20:05:46.726729+00:00
[2024-03-12 15:05:54,529] {data_preprocessing.py:29} INFO - Getting gold data
[2024-03-12 15:05:54,529] {data_preprocessing.py:33} INFO - Getting raw data from ml_lifecycle_airflow/in-vehicle-coupon-recommendation.csv ...
[2024-03-12 15:06:20,212] {data_preprocessing.py:78} INFO - Starting data preprocessing ...
[2024-03-12 15:06:20,425] {data_preprocessing.py:139} INFO - Data preprocessing complete

[2024-03-12 15:06:20,476] {data_preprocessing.py:157} INFO - Encoding features using hashing encoder ...
[2024-03-12 15:07:16,991] {data_preprocessing.py:157} INFO - Encoding features using hashing encoder ...
[2024-03-12 15:08:12,106] {data_preprocessing.py:54} INFO - Uploading preprocessed data to GCS ...
[2024-03-12 15:08:14,536] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/src/features/data_preprocessing.py", line 57, in get_gold_data
    upload_blob(bucket_name, x_train_hashing, path_gold_data + "/x_train.csv")
  File "/Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/src/utils/f_gcs_storage.py", line 29, in upload_blob
    blob.upload_from_filename(source_file_name)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/cloud/storage/blob.py", line 2949, in upload_from_filename
    self._handle_filename_and_upload(
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/cloud/storage/blob.py", line 2815, in _handle_filename_and_upload
    content_type = self._get_content_type(content_type, filename=filename)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/cloud/storage/blob.py", line 1699, in _get_content_type
    content_type, _ = mimetypes.guess_type(filename)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/mimetypes.py", line 290, in guess_type
    return _db.guess_type(url, strict)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/mimetypes.py", line 116, in guess_type
    url = os.fspath(url)
TypeError: expected str, bytes or os.PathLike object, not DataFrame
[2024-03-12 15:08:14,563] {taskinstance.py:1267} INFO - Marking task as FAILED. dag_id=dag_ml_life_cycle, task_id=get_gold_data, execution_date=20240312T200546, start_date=20240312T200554, end_date=20240312T200814
[2024-03-12 15:08:14,574] {standard_task_runner.py:89} ERROR - Failed to execute job 14 for task get_gold_data
Traceback (most recent call last):
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/src/features/data_preprocessing.py", line 57, in get_gold_data
    upload_blob(bucket_name, x_train_hashing, path_gold_data + "/x_train.csv")
  File "/Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/src/utils/f_gcs_storage.py", line 29, in upload_blob
    blob.upload_from_filename(source_file_name)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/cloud/storage/blob.py", line 2949, in upload_from_filename
    self._handle_filename_and_upload(
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/cloud/storage/blob.py", line 2815, in _handle_filename_and_upload
    content_type = self._get_content_type(content_type, filename=filename)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/cloud/storage/blob.py", line 1699, in _get_content_type
    content_type, _ = mimetypes.guess_type(filename)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/mimetypes.py", line 290, in guess_type
    return _db.guess_type(url, strict)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/mimetypes.py", line 116, in guess_type
    url = os.fspath(url)
TypeError: expected str, bytes or os.PathLike object, not DataFrame
[2024-03-12 15:08:14,594] {local_task_job.py:154} INFO - Task exited with return code 1
[2024-03-12 15:08:14,615] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
