[2024-03-20 08:09:03,865] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag_ml_life_cycle.get_gold_data scheduled__2024-03-20T07:53:58.518118+00:00 [queued]>
[2024-03-20 08:09:03,931] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag_ml_life_cycle.get_gold_data scheduled__2024-03-20T07:53:58.518118+00:00 [queued]>
[2024-03-20 08:09:03,931] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-20 08:09:03,931] {taskinstance.py:1239} INFO - Starting attempt 4 of 4
[2024-03-20 08:09:03,931] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-20 08:09:03,939] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): get_gold_data> on 2024-03-20 07:53:58.518118+00:00
[2024-03-20 08:09:03,945] {standard_task_runner.py:52} INFO - Started process 28139 to run task
[2024-03-20 08:09:03,951] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'dag_ml_life_cycle', 'get_gold_data', 'scheduled__2024-03-20T07:53:58.518118+00:00', '--job-id', '1179', '--raw', '--subdir', 'DAGS_FOLDER/lifecycle_ml_example/dags/dag_ml_life_cycle.py', '--cfg-path', '/var/folders/t4/c2kdpvnj6r793w3k056dkc640000gp/T/tmpo5pn92j6', '--error-file', '/var/folders/t4/c2kdpvnj6r793w3k056dkc640000gp/T/tmpo7s99zmw']
[2024-03-20 08:09:03,953] {standard_task_runner.py:77} INFO - Job 1179: Subtask get_gold_data
[2024-03-20 08:09:03,994] {logging_mixin.py:109} INFO - Running <TaskInstance: dag_ml_life_cycle.get_gold_data scheduled__2024-03-20T07:53:58.518118+00:00 [running]> on host 1.0.0.127.in-addr.arpa
[2024-03-20 08:09:04,021] {taskinstance.py:1424} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dag_ml_life_cycle
AIRFLOW_CTX_TASK_ID=get_gold_data
AIRFLOW_CTX_EXECUTION_DATE=2024-03-20T07:53:58.518118+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-03-20T07:53:58.518118+00:00
[2024-03-20 08:09:04,022] {data_preprocessing.py:34} INFO - Random error: 0.13344718713384396
[2024-03-20 08:09:04,022] {data_preprocessing.py:38} INFO - Getting gold data
[2024-03-20 08:09:04,023] {data_preprocessing.py:42} INFO - Getting raw data from ml_lifecycle_airflow/in-vehicle-coupon-recommendation.csv ...
[2024-03-20 08:09:07,665] {data_preprocessing.py:89} INFO - Starting data preprocessing ...
[2024-03-20 08:09:07,812] {data_preprocessing.py:150} INFO - Data preprocessing complete

[2024-03-20 08:09:07,845] {data_preprocessing.py:168} INFO - Encoding features using hashing encoder ...
[2024-03-20 08:09:45,273] {data_preprocessing.py:168} INFO - Encoding features using hashing encoder ...
[2024-03-20 08:09:59,415] {local_task_job.py:191} WARNING - The recorded hostname 1.0.0.127.in-addr.arpa does not match this instance's hostname macbook-pro-2.local
[2024-03-20 08:09:59,434] {process_utils.py:120} INFO - Sending Signals.SIGTERM to group 28139. PIDs of all processes in the group: [28227, 28758, 28759, 28771, 28784, 28921, 28995, 28139]
[2024-03-20 08:09:59,434] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 28139
[2024-03-20 08:09:59,435] {taskinstance.py:1408} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-03-20 08:09:59,457] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/src/features/data_preprocessing.py", line 60, in get_gold_data
    x_test_hashing = encode_features(x_test)
  File "/Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/src/features/data_preprocessing.py", line 173, in encode_features
    hashing_ros_enc = hashing_ros_enc_instance.fit(X=x)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/category_encoders/utils.py", line 315, in fit
    X_transformed = self.transform(X, override_return_df=True)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/sklearn/utils/_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/category_encoders/utils.py", line 488, in transform
    X = self._transform(X)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/category_encoders/hashing.py", line 194, in _transform
    process.start()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 62, in _launch
    f.write(fp.getbuffer())
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1410, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-03-20 08:09:59,470] {taskinstance.py:1267} INFO - Marking task as FAILED. dag_id=dag_ml_life_cycle, task_id=get_gold_data, execution_date=20240320T075358, start_date=20240320T130903, end_date=20240320T130959
[2024-03-20 08:09:59,479] {standard_task_runner.py:89} ERROR - Failed to execute job 1179 for task get_gold_data
Traceback (most recent call last):
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/src/features/data_preprocessing.py", line 60, in get_gold_data
    x_test_hashing = encode_features(x_test)
  File "/Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/src/features/data_preprocessing.py", line 173, in encode_features
    hashing_ros_enc = hashing_ros_enc_instance.fit(X=x)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/category_encoders/utils.py", line 315, in fit
    X_transformed = self.transform(X, override_return_df=True)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/sklearn/utils/_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/category_encoders/utils.py", line 488, in transform
    X = self._transform(X)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/category_encoders/hashing.py", line 194, in _transform
    process.start()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 62, in _launch
    f.write(fp.getbuffer())
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1410, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-03-20 08:09:59,492] {process_utils.py:70} INFO - Process psutil.Process(pid=28921, status='terminated', started='08:09:55') (28921) terminated with exit code None
[2024-03-20 08:09:59,493] {process_utils.py:70} INFO - Process psutil.Process(pid=28758, status='terminated', started='08:09:45') (28758) terminated with exit code None
[2024-03-20 08:09:59,493] {process_utils.py:70} INFO - Process psutil.Process(pid=28784, status='terminated', started='08:09:48') (28784) terminated with exit code None
[2024-03-20 08:09:59,493] {process_utils.py:70} INFO - Process psutil.Process(pid=28995, status='terminated', started='08:09:57') (28995) terminated with exit code None
[2024-03-20 08:09:59,501] {process_utils.py:70} INFO - Process psutil.Process(pid=28227, status='terminated', started='08:09:07') (28227) terminated with exit code None
[2024-03-20 08:09:59,501] {process_utils.py:70} INFO - Process psutil.Process(pid=28771, status='terminated', started='08:09:47') (28771) terminated with exit code None
[2024-03-20 08:09:59,502] {process_utils.py:70} INFO - Process psutil.Process(pid=28139, status='terminated', exitcode=1, started='08:09:03') (28139) terminated with exit code 1
[2024-03-20 08:09:59,502] {process_utils.py:70} INFO - Process psutil.Process(pid=28759, status='terminated', started='08:09:46') (28759) terminated with exit code None
