[2024-03-19 16:49:30,576] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag_ml_life_cycle.evaluate_model scheduled__2024-03-19T16:46:08.348952+00:00 [queued]>
[2024-03-19 16:49:30,588] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dag_ml_life_cycle.evaluate_model scheduled__2024-03-19T16:46:08.348952+00:00 [queued]>
[2024-03-19 16:49:30,588] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-19 16:49:30,588] {taskinstance.py:1239} INFO - Starting attempt 2 of 4
[2024-03-19 16:49:30,588] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-19 16:49:30,598] {taskinstance.py:1259} INFO - Executing <Task(_PythonDecoratedOperator): evaluate_model> on 2024-03-19 16:46:08.348952+00:00
[2024-03-19 16:49:30,606] {standard_task_runner.py:52} INFO - Started process 61744 to run task
[2024-03-19 16:49:30,614] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'dag_ml_life_cycle', 'evaluate_model', 'scheduled__2024-03-19T16:46:08.348952+00:00', '--job-id', '882', '--raw', '--subdir', 'DAGS_FOLDER/lifecycle_ml_example/dags/dag_ml_life_cycle.py', '--cfg-path', '/var/folders/t4/c2kdpvnj6r793w3k056dkc640000gp/T/tmp19rdci70', '--error-file', '/var/folders/t4/c2kdpvnj6r793w3k056dkc640000gp/T/tmpy0q0iquw']
[2024-03-19 16:49:30,617] {standard_task_runner.py:77} INFO - Job 882: Subtask evaluate_model
[2024-03-19 16:49:30,676] {logging_mixin.py:109} INFO - Running <TaskInstance: dag_ml_life_cycle.evaluate_model scheduled__2024-03-19T16:46:08.348952+00:00 [running]> on host macbook-pro-2.local
[2024-03-19 16:49:30,720] {taskinstance.py:1424} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dag_ml_life_cycle
AIRFLOW_CTX_TASK_ID=evaluate_model
AIRFLOW_CTX_EXECUTION_DATE=2024-03-19T16:46:08.348952+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-03-19T16:46:08.348952+00:00
[2024-03-19 16:49:30,721] {dag_ml_life_cycle.py:93} INFO - Getting gold data from ml_lifecycle_airflow/in-vehicle-coupon-recommendation_gold.csv ...
[2024-03-19 16:49:41,556] {local_task_job.py:191} WARNING - The recorded hostname macbook-pro-2.local does not match this instance's hostname 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2024-03-19 16:49:41,575] {process_utils.py:120} INFO - Sending Signals.SIGTERM to group 61744. PIDs of all processes in the group: [61744]
[2024-03-19 16:49:41,575] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 61744
[2024-03-19 16:49:41,575] {taskinstance.py:1408} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-03-19 16:49:41,583] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/dags/dag_ml_life_cycle.py", line 101, in evaluate_model_task
    y_test = get_blob_as_dataframe(
  File "/Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/src/utils/f_gcs_storage.py", line 126, in get_blob_as_dataframe
    blob_content = blob.download_as_string()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/cloud/storage/blob.py", line 1540, in download_as_string
    return self.download_as_bytes(
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/cloud/storage/blob.py", line 1425, in download_as_bytes
    self._prep_and_do_download(
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/cloud/storage/blob.py", line 4352, in _prep_and_do_download
    self._do_download(
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/cloud/storage/blob.py", line 1007, in _do_download
    response = download.consume(transport, timeout=timeout)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/resumable_media/requests/download.py", line 237, in consume
    return _request_helpers.wait_and_retry(
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/resumable_media/requests/_request_helpers.py", line 155, in wait_and_retry
    response = func()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/resumable_media/requests/download.py", line 210, in retriable_request
    result = transport.request(method, url, **request_kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/auth/transport/requests.py", line 537, in request
    self.credentials.before_request(auth_request, method, url, request_headers)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/auth/credentials.py", line 230, in before_request
    self._blocking_refresh(request)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/auth/credentials.py", line 193, in _blocking_refresh
    self.refresh(request)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/oauth2/credentials.py", line 431, in refresh
    ) = reauth.refresh_grant(
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/oauth2/reauth.py", line 332, in refresh_grant
    response_status_ok, response_data, retryable_error = _client._token_endpoint_request_no_throw(
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/oauth2/_client.py", line 215, in _token_endpoint_request_no_throw
    request_succeeded, response_data, retryable_error = _perform_request()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/oauth2/_client.py", line 191, in _perform_request
    response = request(
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/auth/transport/requests.py", line 186, in __call__
    response = self.session.request(
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/http/client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/ssl.py", line 1275, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/ssl.py", line 1133, in read
    return self._sslobj.read(len, buffer)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1410, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-03-19 16:49:41,609] {taskinstance.py:1267} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_ml_life_cycle, task_id=evaluate_model, execution_date=20240319T164608, start_date=20240319T214930, end_date=20240319T214941
[2024-03-19 16:49:41,619] {standard_task_runner.py:89} ERROR - Failed to execute job 882 for task evaluate_model
Traceback (most recent call last):
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/dags/dag_ml_life_cycle.py", line 101, in evaluate_model_task
    y_test = get_blob_as_dataframe(
  File "/Users/macbook/Desktop/airflow_tutorial/airflow/dags/lifecycle_ml_example/src/utils/f_gcs_storage.py", line 126, in get_blob_as_dataframe
    blob_content = blob.download_as_string()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/cloud/storage/blob.py", line 1540, in download_as_string
    return self.download_as_bytes(
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/cloud/storage/blob.py", line 1425, in download_as_bytes
    self._prep_and_do_download(
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/cloud/storage/blob.py", line 4352, in _prep_and_do_download
    self._do_download(
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/cloud/storage/blob.py", line 1007, in _do_download
    response = download.consume(transport, timeout=timeout)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/resumable_media/requests/download.py", line 237, in consume
    return _request_helpers.wait_and_retry(
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/resumable_media/requests/_request_helpers.py", line 155, in wait_and_retry
    response = func()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/resumable_media/requests/download.py", line 210, in retriable_request
    result = transport.request(method, url, **request_kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/auth/transport/requests.py", line 537, in request
    self.credentials.before_request(auth_request, method, url, request_headers)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/auth/credentials.py", line 230, in before_request
    self._blocking_refresh(request)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/auth/credentials.py", line 193, in _blocking_refresh
    self.refresh(request)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/oauth2/credentials.py", line 431, in refresh
    ) = reauth.refresh_grant(
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/oauth2/reauth.py", line 332, in refresh_grant
    response_status_ok, response_data, retryable_error = _client._token_endpoint_request_no_throw(
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/oauth2/_client.py", line 215, in _token_endpoint_request_no_throw
    request_succeeded, response_data, retryable_error = _perform_request()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/oauth2/_client.py", line 191, in _perform_request
    response = request(
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/google/auth/transport/requests.py", line 186, in __call__
    response = self.session.request(
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/http/client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/ssl.py", line 1275, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/ssl.py", line 1133, in read
    return self._sslobj.read(len, buffer)
  File "/Users/macbook/anaconda3/envs/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1410, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-03-19 16:49:41,675] {process_utils.py:70} INFO - Process psutil.Process(pid=61744, status='terminated', exitcode=1, started='16:49:30') (61744) terminated with exit code 1
